name: Deploy Fortiche App

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Login to Docker hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build Docker Image
              run: docker build -t kumarvinayak490/fortiche-app .
            - name: Publish the image to docker hub
              run: docker push kumarvinayak490/fortiche-app:latest 

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from the dockerhub
              run: docker pull kumarvinayak490/fortiche-app:latest
            - name: Run Docker Container
              run: |
                docker run -d -p 3000:3000 --name fortiche-app-container -e NODE_ENV=production -e MONGO_URI=${{ secrets.MONGO_URI }} -e MORGAN=${{ secrets.MORGAN }}  -e SECRET=${{ secrets.SECRET }} kumarvinayak490/fortiche-app:latest